#pragma once
//each value represnts a possiable code in the requests.

#define SIZE_OF_START 5

enum Codes {
	//V1
	LOGIN_REQUEST = 80,
	SIGNUP_REQUEST = 81,

	//V2
	LOGOUT_REQUSET = 82,
	GET_PLAYERS_IN_ROOM_REQUEST = 83,
	JOIN_ROOM_REQUEST = 84,
	CREATE_ROOM_REQUEST = 85,
	HIGH_SCORE_REQUEST = 86,
	GET_ROOMS_REQUEST = 87,
	GET_PERSONAL_STATS_REQUEST = 88,

	//V3
	CLOSE_ROOM_REQUEST = 89,
	START_GAME_REQUEST = 90,
	GET_ROOM_STATE_REQUEST = 91,
	LEAVE_ROOM_REQUEST = 92,

	//v4
	GET_GAME_RESULTS_REQUEST = 93,
	SUBMIT_ANSWER_REQUEST = 94,
	GET_QUESTION_REQUEST = 95,
	LEAVE_GAME_REQUEST = 96,
	DELETE_GAME_REQUEST = 97,
	ADD_QUESTION_REQUEST = 98,

	//V2
	ERROR_RESPONSE = 107,
	LOGIN_RESPONSE = 108,
	SIGNUP_RESPONSE = 109,
	GET_ROOMS_RESPONSE = 110,
	GET_PLAYERS_IN_ROOM_RESPONSE = 111,
	GET_HIGH_SCORE_RESPONSE = 112,
	GET_PERSONAL_STATS_RESPONSE = 113,
	JOIN_ROOM_RESPONSE = 114,
	CREATE_ROOM_RESPONSE = 115,
	LOGOUT_RESPONSE = 116,

	//V3
	CLOSE_ROOM_RESPONSE = 117,
	START_GAME_RESPONSE = 118,
	GET_ROOM_STATE_RESPONSE = 119,
	LEAVE_ROOM_RESPONSE = 120,

	// V4
	GET_GAME_RESULTS_RESPONSE = 121,
	SUBMIT_ANSWER_RESPONSE = 122,
	GET_QUESTION_RESPONSE = 123,
	LEAVE_GAME_RESPONSE = 124,
	DELETE_GAME_RESPONSE= 125,
	ADD_QUESTION_RESPONSE = 126,
};