#pragma once
//each value represnts a possiable code in the requests.

#define SIZE_OF_START 5

enum Codes {
	LOGIN_REQUEST = 100,
	SIGNUP_REQUEST = 101,

	ERROR_RESPONSE = 115,
	LOGIN_RESPONSE = 116,
	SIGNUP_RESPONSE = 117,
	GET_ROOMS_RESPONSE = 118,
	GET_PLAYERS_IN_ROOM_RESPONSE = 119,
	GET_HIGH_SCORE_RESPONSE = 120,
	GET_PERSONAL_STATS_RESPONSE = 121,
	JOIN_ROOM_RESPONSE = 122,
	CREATE_ROOM_RESPONSE = 123,
	LOGOUT_RESPONSE = 124
};